title: tranhl.me
author: Long Tran
email: tranhl@gmx.com
baseurl: "" # Intentionally set to ""
url: "https://tranhl.github.io"
date_format: "%b %-d, %Y"
permalink: /:categories/:title

markdown: kramdown
kramdown:
  input: kramdown
  syntax_highlighter_opts:
    disable: true # Disable rouge highlighter in favour of Prism.js

plugins:
  - jekyll-autoprefixer
  - jekyll-paginate

paginate: 8
paginate_path: "/page-:num"

exclude: [vendor]
sass:
  sass_dir: _sass
  style: compressed
